#!/usr/bin/env tsx
/**
 * Bundle the edge function into a single deployable file.
 *
 * The Supabase CLI without Docker can only deploy single-file functions.
 * This script uses esbuild to bundle all source files (api/*, _shared/*,
 * and @posx/* packages) into one file that the CLI can upload.
 *
 * Usage:
 *   pnpm bundle:edge
 *   # Then: SUPABASE_ACCESS_TOKEN=... npx supabase functions deploy api --project-ref ...
 */
import { build } from 'esbuild';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = typeof import.meta.dirname === 'string'
  ? import.meta.dirname
  : dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

async function main() {
  const result = await build({
    entryPoints: [resolve(ROOT, 'supabase/functions/api/index.ts')],
    bundle: true,
    outfile: resolve(ROOT, 'supabase/functions/api/bundle.ts'),
    format: 'esm',
    platform: 'neutral',
    target: 'esnext',
    // External: these are available in Deno runtime via npm: specifiers
    external: ['postgres', 'ethers', 'bcrypt', 'node:crypto', 'node:fs', 'node:path', 'node:url'],
    // Resolve @posx/* workspace packages
    alias: {
      '@posx/shared-types': resolve(ROOT, 'packages/shared-types/src/index.ts'),
      '@posx/shared-utils': resolve(ROOT, 'packages/shared-utils/src/index.ts'),
      '@posx/domain-rules': resolve(ROOT, 'packages/domain-rules/src/index.ts'),
      '@posx/config': resolve(ROOT, 'packages/config/src/index.ts'),
      '@posx/api-contracts': resolve(ROOT, 'packages/api-contracts/src/index.ts'),
      '@posx/api-contracts/endpoints': resolve(ROOT, 'packages/api-contracts/src/endpoints/index.ts'),
      '@posx/backend-core': resolve(ROOT, 'supabase/functions/_shared/src/index.ts'),
      '@posx/backend-core/db': resolve(ROOT, 'supabase/functions/_shared/src/db/index.ts'),
    },
    // Don't minify — helps with debugging in Supabase logs
    minify: false,
    // Tree-shake unused exports
    treeShaking: true,
    // Keep names for stack traces
    keepNames: true,
    // No source maps — reduces bundle size for edge function limit
    sourcemap: false,
    // No banner — the wrapper is in the index.ts file that imports the bundle
    banner: {
      js: '// Auto-bundled POSX edge function. Generated by: pnpm bundle:edge\n',
    },
    // Rewrite bare npm imports to Deno-compatible npm: specifiers
    plugins: [
      {
        name: 'deno-npm-specifiers',
        setup(pluginBuild) {
          // Map bare module names to Deno npm: specifiers
          // postgres and ethers can use named imports
          pluginBuild.onResolve({ filter: /^postgres$/ }, () => ({
            path: 'npm:postgres@3.4.3', external: true,
          }));
          pluginBuild.onResolve({ filter: /^ethers$/ }, () => ({
            path: 'npm:ethers@6.13.0', external: true,
          }));
          // bcrypt/bcryptjs is CJS — Deno can't do named imports from CJS.
          // We mark it external but post-process the bundle to fix imports.
          pluginBuild.onResolve({ filter: /^bcrypt$/ }, () => ({
            path: '__bcrypt_placeholder__', external: true,
          }));
        },
      },
    ],
  });

  if (result.errors.length > 0) {
    console.error('Bundle failed:', result.errors);
    process.exit(1);
  }

  // Post-process: fix bcrypt CJS imports for Deno compatibility.
  // Deno can't do `import { compareSync } from "npm:bcryptjs"` because
  // bcryptjs is CJS. Replace with default import + destructure.
  const bundlePath = resolve(ROOT, 'supabase/functions/api/bundle.ts');
  const fs2 = await import('node:fs');
  let code = fs2.readFileSync(bundlePath, 'utf8');
  // Replace: import { compareSync } from "__bcrypt_placeholder__";
  // With:    import __bcrypt from "npm:bcryptjs@2.4.3"; const { compareSync } = __bcrypt;
  // Replace ALL bcrypt placeholder imports with a single top-level import
  // and individual destructures.
  const bcryptImports: string[] = [];
  code = code.replace(
    /import\s*\{([^}]+)\}\s*from\s*"__bcrypt_placeholder__"\s*;/g,
    (_match, names) => {
      const cleaned = names.trim();
      bcryptImports.push(cleaned);
      return `var { ${cleaned} } = __bcrypt_mod;`;
    }
  );
  if (bcryptImports.length > 0) {
    // Prepend bcrypt import at the very start of the file
    code = 'import __bcrypt_mod from "npm:bcryptjs@2.4.3";\n' + code;
  }
  fs2.writeFileSync(bundlePath, code);

  console.log('✅ Bundled to supabase/functions/api/bundle.ts');
  console.log('   Warnings:', result.warnings.length);

  const fs = await import('node:fs');
  const indexPath = resolve(ROOT, 'supabase/functions/api/index.ts');
  const originalPath = resolve(ROOT, 'supabase/functions/api/index.original.ts');

  // Backup original
  if (!fs.existsSync(originalPath)) {
    fs.copyFileSync(indexPath, originalPath);
    console.log('   Backed up index.ts -> index.original.ts');
  }

  // Copy bundled output directly as index.ts (single file deploy)
  const outputBundle = resolve(ROOT, 'supabase/functions/api/bundle.ts');
  fs.copyFileSync(outputBundle, indexPath);
  fs.unlinkSync(outputBundle);
  console.log('   Replaced index.ts with bundled version (single file)');
  console.log('');
  console.log('Ready to deploy:');
  console.log('  SUPABASE_ACCESS_TOKEN=... npx supabase functions deploy api --project-ref kzznfhtcevzysztzahzl --no-verify-jwt');
  console.log('');
  console.log('After deploy, restore original:');
  console.log('  pnpm restore:edge');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
